language: node_js
node_js:
  - 9
before_install:
  - npm config set depth 0
cache:
  directories:
    - "node_modules"
script:
  - npm run lint
  - npm run test
  - npm run build
  - nyc --silent npm run test
  - nyc report --reporter=text-lcov | coveralls
  - nyc check-coverage --lines 90
after_success:
  - npm run build
  - semantic-release
notifications:
  email: false
sudo: false
